[package]
name = "aichess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"
resvg = "0.36.0"
rstest = "0.18.2"
toto = "0.1.0"

serde = { version = "1.0", features = ["derive"] }
#serde_derive = "1.0"
serde_json = "1.0"
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
mocats = "0.3.0"
burn = "0.15.0"
resnet-burn = { git = "https://github.com/tracel-ai/models", branch = "main", path = "resnet-burn" }

[[bin]]
name = "fen2svg"
path = "src/bin/fen2svg.rs"


[dev-dependencies]
